package ee.qrent.notification.email.api.in.request;

public enum EmailType {
  MONDAY_FINANCIAL_EMAIL,
  INVOICE_EMAIL,
  CONTRACT_EMAIL,
  AUTHORIZATION_EMAIL,
  USER_REGISTRATION_EMAIL,
  RENT_CALCULATION_EMAIL,
  OBLIGATION_CALCULATION_EMAIL,
  BONUS_CALCULATION_EMAIL,
  ERROR_EMAIL
}
