rootProject.name = "qrent"

pluginManagement {
    repositories.gradlePluginPortal()
}

dependencyResolutionManagement {
    repositories.mavenCentral()
}

include("source:common:api")
include("source:common:core")
include("source:common:utils")
include("source:common:config")

include("source:queue:api:in")
include("source:queue:api:out")
include("source:queue:core")
include("source:queue:domain")
include("source:queue:config")
include("source:queue:persistence:adapter")
include("source:queue:persistence:entity")
include("source:queue:persistence:repository")

include("source:notification:app")
include("source:notification:rest")
include("source:notification:domain:email:api:in")
include("source:notification:domain:email:api:out")
include("source:notification:domain:email:domain")
include("source:notification:domain:email:core")
include("source:notification:domain:email:config")
include("source:notification:domain:email:persistence:adapter")
include("source:notification:domain:email:persistence:entity")
include("source:notification:domain:email:persistence:repository")
include("source:notification:domain:email:persistence:flyway")
include("source:notification:task:core")
include("source:notification:task:config")

include("source:billing:app")
include("source:billing:ui-thymeleaf")
include("source:billing:task:config")
include("source:billing:task:core")
include("source:billing:security:api:in")
include("source:billing:security:core")
include("source:billing:security:config")

include("source:billing:domain:driver:api:in")
include("source:billing:domain:driver:api:out")
include("source:billing:domain:driver:domain")
include("source:billing:domain:driver:core")
include("source:billing:domain:driver:persistence:adapter")
include("source:billing:domain:driver:persistence:entity")
include("source:billing:domain:driver:persistence:repository")
include("source:billing:domain:driver:persistence:flyway")
include("source:billing:domain:driver:config")

include("source:billing:domain:car:api:in")
include("source:billing:domain:car:api:out")
include("source:billing:domain:car:domain")
include("source:billing:domain:car:core")
include("source:billing:domain:car:persistence:adapter")
include("source:billing:domain:car:persistence:entity")
include("source:billing:domain:car:persistence:repository")
include("source:billing:domain:car:persistence:flyway")
include("source:billing:domain:car:config")

include("source:billing:domain:firm:api:in")
include("source:billing:domain:firm:api:out")
include("source:billing:domain:firm:domain")
include("source:billing:domain:firm:core")
include("source:billing:domain:firm:persistence:adapter")
include("source:billing:domain:firm:persistence:entity")
include("source:billing:domain:firm:persistence:repository")
include("source:billing:domain:firm:persistence:flyway")
include("source:billing:domain:firm:config")

include("source:billing:domain:bonus:api:in")
include("source:billing:domain:bonus:api:out")
include("source:billing:domain:bonus:domain")
include("source:billing:domain:bonus:core")
include("source:billing:domain:bonus:persistence:adapter")
include("source:billing:domain:bonus:persistence:entity")
include("source:billing:domain:bonus:persistence:repository")
include("source:billing:domain:bonus:persistence:flyway")
include("source:billing:domain:bonus:config")

include("source:billing:domain:constant:api:in")
include("source:billing:domain:constant:api:out")
include("source:billing:domain:constant:domain")
include("source:billing:domain:constant:core")
include("source:billing:domain:constant:persistence:adapter")
include("source:billing:domain:constant:persistence:entity")
include("source:billing:domain:constant:persistence:repository")
include("source:billing:domain:constant:persistence:flyway")
include("source:billing:domain:constant:config")

include("source:billing:domain:invoice:api:in")
include("source:billing:domain:invoice:api:out")
include("source:billing:domain:invoice:domain")
include("source:billing:domain:invoice:core")
include("source:billing:domain:invoice:persistence:adapter")
include("source:billing:domain:invoice:persistence:entity")
include("source:billing:domain:invoice:persistence:repository")
include("source:billing:domain:invoice:persistence:flyway")
include("source:billing:domain:invoice:config")

include("source:billing:domain:insurance:api:in")
include("source:billing:domain:insurance:api:out")
include("source:billing:domain:insurance:domain")
include("source:billing:domain:insurance:core")
include("source:billing:domain:insurance:persistence:adapter")
include("source:billing:domain:insurance:persistence:entity")
include("source:billing:domain:insurance:persistence:repository")
include("source:billing:domain:insurance:persistence:flyway")
include("source:billing:domain:insurance:config")

include("source:billing:domain:contract:api:in")
include("source:billing:domain:contract:api:out")
include("source:billing:domain:contract:domain")
include("source:billing:domain:contract:core")
include("source:billing:domain:contract:persistence:adapter")
include("source:billing:domain:contract:persistence:entity")
include("source:billing:domain:contract:persistence:repository")
include("source:billing:domain:contract:persistence:flyway")
include("source:billing:domain:contract:config")

include("source:billing:domain:transaction:api:in")
include("source:billing:domain:transaction:api:out")
include("source:billing:domain:transaction:domain")
include("source:billing:domain:transaction:core")
include("source:billing:domain:transaction:persistence:adapter")
include("source:billing:domain:transaction:persistence:entity")
include("source:billing:domain:transaction:persistence:repository")
include("source:billing:domain:transaction:persistence:flyway")
include("source:billing:domain:transaction:config")

include("source:billing:domain:bonus:api:in")
include("source:billing:domain:bonus:api:out")
include("source:billing:domain:bonus:domain")
include("source:billing:domain:bonus:core")
include("source:billing:domain:bonus:persistence:adapter")
include("source:billing:domain:bonus:persistence:entity")
include("source:billing:domain:bonus:persistence:repository")
include("source:billing:domain:bonus:persistence:flyway")
include("source:billing:domain:bonus:config")

include("source:billing:domain:user:api:in")
include("source:billing:domain:user:api:out")
include("source:billing:domain:user:domain")
include("source:billing:domain:user:core")
include("source:billing:domain:user:persistence:adapter")
include("source:billing:domain:user:persistence:entity")
include("source:billing:domain:user:persistence:repository")
include("source:billing:domain:user:persistence:flyway")
include("source:billing:domain:user:config")

