create table if not exists weekly_report
(
    id                              serial primary key,
    q_week_id                       integer        not null,
    FOREIGN KEY (q_week_id) REFERENCES q_week (id),
    driver_id                       integer        not null,
    FOREIGN KEY (driver_id) REFERENCES driver (id),
    call_sign_id                    integer        not null,
    FOREIGN KEY (call_sign_id) REFERENCES call_sign (id),
    car_id                          integer        not null,
    FOREIGN KEY (car_id) REFERENCES car (id),
    q_firm_id                       integer        not null,
    FOREIGN KEY (q_firm_id) REFERENCES firm (id),
    obligation_status               varchar        not null,
    obligation_total                numeric(10, 2) not null,
    obligation_rent                 numeric(10, 2) not null,
    obligation_debt                 numeric(10, 2) not null,
    obligation_repairment           numeric(10, 2) not null,
    obligation_repairment_franchise numeric(10, 2) not null,
    obligation_others               numeric(10, 2) not null,
    obligation_fee                  numeric(10, 2) not null,
    bonus_new_driver                numeric(10, 2) not null,
    bonus_reliable_partner          numeric(10, 2) not null,
    bonus_bolt                      numeric(10, 2) not null,
    bonus_friend                    numeric(10, 2) not null,
    obligation_adjustment_bolt      numeric(10, 2) not null,
    obligation_adjustment_forus     numeric(10, 2) not null,
    prepayment                      numeric(10, 2) not null,
    comment                         varchar
);