create table if not exists weekly_report
(
    id                              serial primary key,
    q_week_id                       integer not null,
    FOREIGN KEY (q_week_id) REFERENCES q_week (id),
    driver_id                       integer not null,
    FOREIGN KEY (driver_id) REFERENCES driver (id),
    call_sign_id                    integer not null,
    FOREIGN KEY (call_sign_id) REFERENCES call_sign (id),
    car_id                          integer not null,
    FOREIGN KEY (car_id) REFERENCES car (id),
    q_firm_id                       integer not null,
    FOREIGN KEY (q_firm_id) REFERENCES q_firm (id),
    obligation_status               varchar not null,
    obligation_total                number  not null,
    obligation_rent                 number  not null,
    obligation_debt                 number  not null,
    obligation_repairment           number  not null,
    obligation_repairment_franchise number  not null,
    obligation_others               number  not null,
    obligation_fee                  number  not null,
    bonus_new_driver                number  not null,
    bonus_reliable_partner          number  not null,
    bonus_bolt                      number  not null,
    bonus_friend                    number  not null,
    obligation_adjustment_bolt      number  not null,
    obligation_adjustment_forus     number  not null,
    prepayment                      number  not null,
    comment                         varchar
);