package ee.qrental.email.api.in.request;

public enum EmailType {
  INVOICE,
  CONTRACT,
  AUTHORIZATION,
  USER_REGISTRATION,
  RENT_CALCULATION,
  OBLIGATION_CALCULATION,
  BONUS_CALCULATION,
  ERROR
}
