package ee.qrent.queue.api.in;

public enum EntryType {
  INFO_REPORT_EMAIL,
  TUESDAY_REPORT_EMAIL,
  WEDNESDAY_REPORT_EMAIL,
  FRIDAY_REPORT_EMAIL,
  INVOICE_EMAIL,
  CONTRACT_EMAIL,
  AUTHORIZATION_EMAIL,
  USER_REGISTRATION_EMAIL,
  RENT_CALCULATION_EMAIL,
  OBLIGATION_CALCULATION_EMAIL,
  BONUS_CALCULATION_EMAIL,
  BRANDING_VERIFICATION_EMAIL,
  ERROR_EMAIL
}
